### ISSUE TITLE
Frontend fuer Ldappasswd schreiben

### ISSUE THREAD

**Issue by jlauinger** [d120/shell#3]
Write easy frontend to reset user passwords

Either write own ldap command, or use ldappasswd as backend:

ldappasswd -x -Duid=fssUser,ou=People,dc=fachschaft,dc=informatik,dc=tu-darmstadt,dc=de -W -s "newPW" uid=changedUser,ou=People,dc=fachschaft,dc=informatik,dc=tu-darmstadt,dc=de

via @jnhmn

**Comment by luelista** [comment]
Einfach unter https://glados.d120.de/usermgmt/listusers.php auf den Schraubenschlüssel klicken

**Comment by jnhmn** [comment]
Einfach folgende Funktion in eure zshrc oder bashrc schreiben und schon verhält es sich fast wie passwd:

```bash
ldappasswd () {
if [ -z "${1}" ]; then
  echo "Change own password"
  /usr/bin/ldappasswd -x -SW -Duid=$USER,ou=People,dc=fachschaft,dc=informatik,dc=tu-darmstadt,dc=de
else
  echo "Reset password for $1"
  /usr/bin/ldappasswd -x -SW -Duid=$USER,ou=People,dc=fachschaft,dc=informatik,dc=tu-darmstadt,dc=de uid=$1,ou=People,dc=fachschaft,dc=informatik,dc=tu-darmstadt,dc=de
fi
}
```

**Comment by miterion** [comment]
Kann das Issue geschlossen werden? @jlauinger  @jnhmn
