### ISSUE TITLE
Cannot list fss

### ISSUE THREAD

**Issue by jlauinger** [d120/shell#5]
```
> d120-groupmod list fss
Please enter password for user:
Error: uid not found in cn=admin,cn=config.
```

via @exploide

**Comment by jnhmn** [comment]
Ist auf glados gefixt. Durch den Umzug der GIT-Repos kann ich das aber gerade nicht committen. Vielleicht will jemand anderes sich mal darum kümmern, dass /opt/d120/lda-scripts wieder ein funktionierendes GIT-Repo ist :P
